name: CI

on:
  pull_request:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  # Use the same Rust toolchain across jobs so they can share a cache.
  toolchain: nightly-2025-06-26

jobs:
  clippy-lints:
    name: Clippy lints
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      RUSTFLAGS: -Dwarnings -Zshare-generics=y -Zthreads=0
      RUSTDOCFLAGS: -Dwarnings -Zshare-generics=y -Zthreads=0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.toolchain }}
          components: clippy

      - name: Restore Rust cache
        id: cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ci
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install build dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev

      - name: Run Clippy lints
        run: cargo clippy --locked --workspace --all-targets --profile ci --all-features

  format:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      RUSTFLAGS: -Dwarnings -Zshare-generics=y -Zthreads=0
      RUSTDOCFLAGS: -Dwarnings -Zshare-generics=y -Zthreads=0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.toolchain }}
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --all -- --check

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings -Zshare-generics=y -Zthreads=0
      RUSTDOCFLAGS: -Dwarnings -Zshare-generics=y -Zthreads=0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.toolchain }}

      - name: Restore Rust cache
        id: cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ci
          save-if: false

      - name: Install build dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev

      - name: Check documentation
        run: cargo doc --locked --workspace --profile ci --all-features --document-private-items --no-deps

  test:
    name: Tests
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Zshare-generics=y -Zthreads=0
      RUSTDOCFLAGS: -Zshare-generics=y -Zthreads=0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: echo "RUSTFLAGS=${RUSTFLAGS:+$RUSTFLAGS }-Zcodegen-backend=cranelift" >> "${GITHUB_ENV}"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.toolchain }}
          components: rustc-codegen-cranelift-preview

      - name: Restore Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: test
          cache-directories: ${{ env.LD_LIBRARY_PATH }}
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install build dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev

      - name: Run tests
        run: cargo test --locked --workspace --lib --bins --tests --examples --profile ci --no-fail-fast --all-features

  bevy-lints:
    name: Bevy lints
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      RUSTFLAGS: -Dwarnings -Zshare-generics=y -Zthreads=0
      RUSTDOCFLAGS: -Dwarnings -Zshare-generics=y -Zthreads=0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain (plus bevy_lint)
        uses: TheBevyFlock/bevy_cli/bevy_lint@lint-v0.4.0
        with:
          cache: true
          save-cache-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Restore Rust cache
        id: cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ci
          save-if: false

      - name: Install build dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev

      - name: Run Bevy lints
        run: bevy_lint --locked --workspace --all-targets --profile ci --all-features
